version: '3.8'

services:
  kafka:
    image: docker.io/bitnami/kafka:3.6
    container_name: kafka
    ports:
      - '9092:9092'
      - '9094:9094'
    expose:
      - '9094'
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      # KRaft settings
      - KAFKA_KRAFT_ENABLE=yes
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes

  kafka-init:
    image: docker.io/bitnami/kafka:3.6
    command:
      - '/bin/bash'
      - '-c'
      - |
        /opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic listing-recommendation-requests
        /opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic listing-recommendation-responses
        /opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic profile-recommendation-requests
        /opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic profile-recommendation-responses
    depends_on:
      - kafka
    init: true

networks:
  default:
    driver: bridge

volumes:
  kafka_data:
    driver: local
